#version 460 core
#extension GL_GOOGLE_include_directive : require

// It's point, spot, flashlight and sun
#define LIGHT_POINT 1

// It's global illumination diffuse bounces lighting pass
#define GLOBAL_ILLUMINATION 1

// Soft lighting can be sampled with agressive optimization
#define ONE_LIGHT_PER_TEXEL 1

//#define IRRADIANCE_MULTIPLIER 10.

#define OUTPUTS RAY_LIGHT_INDIRECT_POINT_OUTPUTS
#include "ray_light_direct.glsl"
