#version 460 core
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_ray_tracing : require
#define GLSL
#include "ray_interop.h"
#undef GLSL
#define TRACE_POST_LAUNCH_ID gl_LaunchIDEXT.xy
#define TRACE_POST_HIT_POS bounce_hit_pos
#define TRACE_POST_NORMALS bounce_normals_gs
#define TRACE_POST_OUT_BASE_COLOR out_bounce_base_color_a
#define TRACE_POST_OUT_MATERIAL out_bounce_material_rmxx
#include "trace_post_decals_surface.glsl"
