#version 460 core
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_ray_tracing : require
#define GLSL
#include "ray_interop.h"
#undef GLSL
#define TRACE_POST_REFLECTION 0
#define TRACE_POST_LAUNCH_ID gl_LaunchIDEXT.xy
#define TRACE_POST_RAY_ORIGIN_LENGTH bounce_ray_origin_length
#define TRACE_POST_VIEW_DIR bounce_view_dir
#define TRACE_POST_OUT_THROUGHPUT out_bounce_throughput
#define TRACE_POST_OUT_EMISSIVE out_bounce_emissive
#include "trace_post_legacy_surface.glsl"
