// Pass toggles in rt.json order (denoiser-related chain).
#define DENOISER_ENABLE_STABILIZE_RESERVOIRS 1
#define DENOISER_ENABLE_DIFFUSE_SAMPLING_FILTER 1
#define DENOISER_ENABLE_SHADOWS_FILTERING 1
#define DENOISER_ENABLE_SHADOW_MASK_CATMULL_ROM 1
#define DENOISER_ENABLE_SPATIAL_RECONSTRUCTION 1
#define DENOISER_ENABLE_REPROJECTION 1
#define DENOISER_ENABLE_ATROUS 0
#define DENOISER_ENABLE_DEFLICKERING 0

// Diffuse sampling filter.
#define DENOISER_SPATIAL_DIFFUSE_ENABLE 1
#define DENOISER_SPATIAL_SPECULAR_ENABLE 1
#define DENOISER_SPATIAL_CONFIDENCE_SCALE_DIFFUSE 1.0
#define DENOISER_SPATIAL_RECONSTRUCTION_CONF_MULT 0.1

// Shadow filtering and shadow-mask reconstruction.
#define DENOISER_SHADOW_MASK_ATROUS_MAX_STEP 8
#define DENOISER_SHADOW_MASK_CATMULL_RADIUS 16

// Spatial reconstruction.
#define DENOISER_SPATIAL_CONFIDENCE_SCALE_SPECULAR 1.0

// Firefly rejection.
#define DENOISER_ENABLE_PRE_FIREFLY_REJECTION_DIFFUSE 1
#define DENOISER_ENABLE_PRE_FIREFLY_REJECTION_SPECULAR 1

// Direct diffuse/specular a-trous.
#define DENOISER_MAX_ATROUS_STEP_DIFFUSE 8
#define DENOISER_MAX_ATROUS_STEP_SPECULAR 8

// Post-a-trous reprojection reset.
#define DENOISER_DIFFUSE_POST_ATROUS_LUMA_RESET_THRESHOLD 0.05
#define DENOISER_DIFFUSE_POST_ATROUS_LUMA_RESET_FADE_END 0.2
#define DENOISER_DIFFUSE_POST_ATROUS_MAX_HISTORY 4.0
#define DENOISER_SPECULAR_POST_ATROUS_LUMA_RESET_THRESHOLD 0.02
#define DENOISER_SPECULAR_POST_ATROUS_LUMA_RESET_FADE_END 0.2
#define DENOISER_SPECULAR_POST_ATROUS_MAX_HISTORY 8.0

// Debug views.
#define DENOISER_DEBUG_CONFIDENCE_VIEW 0
#define DENOISER_DEBUG_SHADOW_MASK_VIEW 0
#define DENOISER_DEBUG_DIRECT_DIFFUSE_ATROUS_VARIANCE 0

// Legacy shared constants.
#define NEAR_PLANE_OFFSET 5.
#define GI_DOWNSAMPLE 2
#define GI_BOUNCES_MAX 1
