#version 460
#include "debug.glsl"
#include "utils.glsl"
#include "color_spaces.glsl"
#include "brdf.h"
#include "lighting_utils.glsl"

#define GLSL
#include "ray_interop.h"
#undef GLSL

#define DIFFUSE_TEMPORAL_HISTORY_MIX_WEIGHT 0.5
#define SPECULAR_TEMPORAL_HISTORY_MIX_WEIGHT 0.5
#define DIELECTRIC_SPECULAR_MULTIPLIER 0.02 // default value from pbr papers, but 0.04 in Unreal Engine

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba16f) uniform image2D out_final_image;

layout(set = 0, binding = 1, rgba8) uniform readonly image2D base_color_a;

layout(set = 0, binding = 2, rgba16f) uniform readonly image2D diffuse_asvgf;
layout(set = 0, binding = 3, rgba16f) uniform readonly image2D specular_asvgf;

layout(set = 0, binding = 4, rgba16f) uniform readonly image2D indirect_diffuse_asvgf;
layout(set = 0, binding = 5, rgba16f) uniform readonly image2D indirect_specular_asvgf;

layout(set = 0, binding = 6, rgba16f) uniform readonly image2D emissive;

layout(set = 0, binding = 7, rgba32f) uniform readonly image2D position_t;
layout(set = 0, binding = 8, rgba16f) uniform readonly image2D normals_gs;
layout(set = 0, binding = 9, rgba8) uniform readonly image2D material_rmxx;

layout(set = 0, binding = 10) uniform UBO { UniformBuffer ubo; } ubo;

//#define DEBUG_NOISE
#ifdef DEBUG_NOISE
layout(set = 0, binding = 9) uniform sampler3D blue_noise_texture;
#include "bluenoise.glsl"
#endif

layout(set = 0, binding = 10, rgba16f) uniform readonly image2D legacy_blend;

//layout(set = 0, binding = 11) uniform sampler2D textures[MAX_TEXTURES];

#include "atrous.glsl"

const int INDIRECT_SCALE = 2;

// Blatantly copypasted from https://www.shadertoy.com/view/XsGfWV
vec3 aces_tonemap(vec3 color){
	mat3 m1 = mat3(
		0.59719, 0.07600, 0.02840,
		0.35458, 0.90834, 0.13383,
		0.04823, 0.01566, 0.83777
	);
	mat3 m2 = mat3(
		1.60475, -0.10208, -0.00327,
		-0.53108,  1.10813, -0.07276,
		-0.07367, -0.00605,  1.07602
	);
	vec3 v = m1 * color;
	vec3 a = v * (v + 0.0245786) - 0.000090537;
	vec3 b = v * (0.983729 * v + 0.4329510) + 0.238081;
	//return pow(clamp(m2 * (a / b), 0.0, 1.0), vec3(1.0 / 2.2));
	return clamp(m2 * (a / b), 0.0, 1.0);
}

vec3 reinhard(vec3 color){
	return color / (color + 1.0);
}

vec3 reinhard02(vec3 c, vec3 Cwhite2) {
	return c * (1. + c / Cwhite2) / (1. + c);
}

float normpdf2(in float x2, in float sigma) { return 0.39894*exp(-0.5*x2/(sigma*sigma))/sigma; }
float normpdf(in float x, in float sigma) { return normpdf2(x*x, sigma); }

void readNormals(ivec2 uv, out vec3 geometry_normal, out vec3 shading_normal) {
	const vec4 n = imageLoad(normals_gs, uv);
	geometry_normal = normalDecode(n.xy);
	shading_normal = normalDecode(n.zw);
}

vec3 closestColor(vec3 color1, vec3 color2, vec3 sampleColor) {
    float dist1 = dot(color1 - sampleColor, color1 - sampleColor);
    float dist2 = dot(color2 - sampleColor, color2 - sampleColor);
    return (dist1 < dist2) ? color1 : color2;
}

struct Components {
	vec3 direct_diffuse, direct_specular, indirect_diffuse, indirect_specular;
};

vec3 restoreSpecular(vec3 decolorized_specular, vec3 base_color, float fresnel, float metalness) {
	const vec3 plasticSpecular = decolorized_specular * mix(DIELECTRIC_SPECULAR_MULTIPLIER, 1.0, fresnel);
	const vec3 metalSpecular = decolorized_specular * base_color;
	return mix(plasticSpecular, metalSpecular, metalness);
}

void main() {
	const ivec2 res = ivec2(vec2(ubo.ubo.res) * ubo.ubo.resScale);
	const ivec2 pix = ivec2(gl_GlobalInvocationID);

	if (any(greaterThanEqual(pix, res))) {
		return;
	}

	const vec3 position = imageLoad(position_t, pix).xyz;

	const vec3 base_color = SRGBtoLINEAR(imageLoad(base_color_a, pix).rgb);

	const vec4 material_rmxx_sample = imageLoad(material_rmxx, pix);
	const float roughness = material_rmxx_sample.r;
	const float metalness = material_rmxx_sample.g;

	vec3 geometry_normal, shading_normal;
	readNormals(pix, geometry_normal, shading_normal);

	if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_DISABLED) {
		// no-op, just continue
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_BASECOLOR) {
		imageStore(out_final_image, pix, vec4(LINEARtoSRGB(imageLoad(base_color_a, pix).rgb), 0.)); return;
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_BASEALPHA) {
		imageStore(out_final_image, pix, imageLoad(base_color_a, pix).aaaa); return;
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_EMISSIVE) {
		imageStore(out_final_image, pix, vec4(LINEARtoSRGB(imageLoad(emissive, pix).rgb), 0.)); return;
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_MATERIAL) {
		imageStore(out_final_image, pix, vec4(imageLoad(material_rmxx, pix).rg, 0., 0.)); return;
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_NSHADE) {
		imageStore(out_final_image, pix, vec4(.5 + shading_normal * .5, 0.));
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_NGEOM) {
		imageStore(out_final_image, pix, vec4(.5 + geometry_normal * .5, 0.));
		return;
	}

#ifdef DEBUG_NOISE
	imageStore(out_final_image, pix, blueNoise(ivec3(pix.xy, ubo.ubo.frame_counter))); return;
#endif

	Components c;
	c.direct_diffuse = imageLoad(diffuse_asvgf, pix).rgb;
	c.direct_specular = imageLoad(specular_asvgf, pix).rgb;
	c.indirect_specular = imageLoad(indirect_specular_asvgf, pix).rgb;
	c.indirect_diffuse = imageLoad(indirect_diffuse_asvgf, pix).rgb;

	if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_DISABLED) {
		// Skip
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_DIRECT) {
		imageStore(out_final_image, pix, vec4(LINEARtoSRGB(c.direct_diffuse + c.direct_specular), 0.)); return;
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_DIRECT_DIFF) {
		imageStore(out_final_image, pix, vec4(LINEARtoSRGB(c.direct_diffuse), 0.)); return;
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_DIRECT_SPEC) {
		imageStore(out_final_image, pix, vec4(LINEARtoSRGB(c.direct_specular), 0.)); return;
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_INDIRECT) {
		imageStore(out_final_image, pix, vec4(LINEARtoSRGB(c.indirect_diffuse + c.indirect_specular), 0.)); return;
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_INDIRECT_SPEC) {
		imageStore(out_final_image, pix, vec4(LINEARtoSRGB(c.indirect_specular), 0.)); return;
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_INDIRECT_DIFF) {
		imageStore(out_final_image, pix, vec4(LINEARtoSRGB(c.indirect_diffuse), 0.)); return;
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_DIFFUSE) {
		imageStore(out_final_image, pix, vec4(LINEARtoSRGB(c.indirect_diffuse + c.direct_diffuse), 0.)); return;
		return;
	} else if (ubo.ubo.debug_display_only == DEBUG_DISPLAY_SPECULAR) {
		imageStore(out_final_image, pix, vec4(LINEARtoSRGB(c.indirect_specular + c.direct_specular), 0.)); return;
		return;
	}

	vec3 diffuse = c.direct_diffuse + c.indirect_diffuse;
	vec3 specular = c.direct_specular + c.indirect_specular;

#ifdef DEBUG_VALIDATE_EXTRA
	if (IS_INVALIDV(diffuse)) {
		debugPrintfEXT("pix=(%d,%d) diffuse=inv", pix.x, pix.y);
		diffuse = vec3(0.);
	}

	if (IS_INVALIDV(specular)) {
		debugPrintfEXT("pix=(%d,%d) new_specular=inv, specular=(%f, %f, %f) history_specular=(%f, %f, %f)",
			pix.x, pix.y,
			specular.r, specular.g, specular.b,
			);
		specular = vec3(0.);
	}
#endif

	DEBUG_VALIDATE_RANGE_VEC3("denoiser.diffuse", diffuse, 0., 1e6);
	DEBUG_VALIDATE_RANGE_VEC3("denoiser.specular", specular, 0., 1e6);

	vec3 colour = vec3(0.);

	if (ubo.ubo.debug_display_only != DEBUG_DISPLAY_LIGHTING) {
		vec3 origin = (ubo.ubo.inv_view * vec4(0, 0, 0, 1)).xyz;
		const vec3 V = normalize(origin - position);
		colour.rgb = composePBRFromLobes(
				diffuse,
				specular,
				base_color,
				metalness,
				roughness,
				shading_normal,
				V);
	} else {
		colour = diffuse + specular;
	}

	//colour = specular;

	const vec4 legacy_blend = imageLoad(legacy_blend, pix);

	colour += imageLoad(emissive, pix).rgb;
	// Revealage. TODO: which colorspace?
	colour *= legacy_blend.a;

	colour = LINEARtoSRGB(colour);

// See issue https://github.com/w23/xash3d-fwgs/issues/668, map test_blendmode_additive_alpha.
// Adding emissive_blend to the final color in the *incorrect* sRGB-γ space. It makes
// it look much more like the original. Adding emissive in the *correct* linear space differs
// from the original a lot, and looks perceptively worse.
	colour += legacy_blend.rgb;

	DEBUG_VALIDATE_RANGE_VEC3("denoiser.colour", colour, 0., 1e6);

	imageStore(out_final_image, pix, vec4(colour, 0./*unused*/));
}
