#ifndef DENOISER_CONFIG_GLSL_INCLUDED
#define DENOISER_CONFIG_GLSL_INCLUDED

// Master toggles for denoiser stages.
#ifndef DENOISER_ENABLE_SHADOWS_FILTERING
#define DENOISER_ENABLE_SHADOWS_FILTERING 1
#endif

#ifndef DENOISER_ENABLE_SPATIAL_RECONSTRUCTION
#define DENOISER_ENABLE_SPATIAL_RECONSTRUCTION 1
#endif

#ifndef DENOISER_ENABLE_SPATIAL_RECONSTRUCTION_DIFFUSE
#define DENOISER_ENABLE_SPATIAL_RECONSTRUCTION_DIFFUSE 1
#endif

#ifndef DENOISER_ENABLE_SPATIAL_RECONSTRUCTION_SPECULAR
#define DENOISER_ENABLE_SPATIAL_RECONSTRUCTION_SPECULAR 1
#endif

#ifndef DENOISER_ENABLE_DIFFUSE_SAMPLING_FILTER
#define DENOISER_ENABLE_DIFFUSE_SAMPLING_FILTER 1
#endif

#ifndef DENOISER_SPATIAL_CONFIDENCE_SCALE_DIFFUSE
#define DENOISER_SPATIAL_CONFIDENCE_SCALE_DIFFUSE 1.0
#endif

#ifndef DENOISER_SPATIAL_CONFIDENCE_SCALE_SPECULAR
#define DENOISER_SPATIAL_CONFIDENCE_SCALE_SPECULAR 1.0
#endif

#ifndef DENOISER_DEBUG_CONFIDENCE_VIEW
#define DENOISER_DEBUG_CONFIDENCE_VIEW 0
#endif

#ifndef DENOISER_DEBUG_SHADOW_MASK_VIEW
#define DENOISER_DEBUG_SHADOW_MASK_VIEW 0
#endif

#ifndef DENOISER_ENABLE_SHADOW_MASK_ATROUS
#define DENOISER_ENABLE_SHADOW_MASK_ATROUS 0
#endif

#ifndef DENOISER_SHADOW_MASK_ATROUS_MAX_STEP
#define DENOISER_SHADOW_MASK_ATROUS_MAX_STEP 8
#endif

#ifndef DENOISER_ENABLE_SHADOW_MASK_CATMULL_ROM
#define DENOISER_ENABLE_SHADOW_MASK_CATMULL_ROM 1
#endif

#ifndef DENOISER_SHADOW_MASK_CATMULL_RADIUS
#define DENOISER_SHADOW_MASK_CATMULL_RADIUS 16
#endif

#ifndef DENOISER_SPATIAL_RECONSTRUCTION_CONF_MULT
#define DENOISER_SPATIAL_RECONSTRUCTION_CONF_MULT 0.1
#endif

#ifndef DENOISER_ENABLE_REPROJECTION
#define DENOISER_ENABLE_REPROJECTION 1
#endif

#ifndef DENOISER_ENABLE_ATROUS
#define DENOISER_ENABLE_ATROUS 1
#endif

#ifndef DENOISER_DEBUG_DIRECT_DIFFUSE_ATROUS_VARIANCE
#define DENOISER_DEBUG_DIRECT_DIFFUSE_ATROUS_VARIANCE 0
#endif

// Per-lobe max allowed a-trous step; larger steps are bypassed.
#ifndef DENOISER_MAX_ATROUS_STEP_DIFFUSE
#define DENOISER_MAX_ATROUS_STEP_DIFFUSE 8
#endif

#ifndef DENOISER_MAX_ATROUS_STEP_SPECULAR
#define DENOISER_MAX_ATROUS_STEP_SPECULAR 8
#endif


// not plane, it's sphere, but working
#define NEAR_PLANE_OFFSET 5.

// we downsample gi map and store bounces positions in neighboor texels
// downsample image dimensions by 2 = store 4 bounces
// downsample image dimensions by 3 = store 9 bounces

#ifndef GI_DOWNSAMPLE
#define GI_DOWNSAMPLE 2
#endif

// max bounces for testing bounces visiblity
#define GI_BOUNCES_MAX 1

#endif
