#version 460 core
#extension GL_GOOGLE_include_directive : require

#define OUTPUT_DIRECT out_specular_direct_shadowed_prefirefly
#define INPUT_DIRECT specular_direct_shadowed

#include "denoiser_config.glsl"

#define FIREFLY_REJECTION_ENABLE DENOISER_ENABLE_PRE_FIREFLY_REJECTION_SPECULAR
#define FIREFLY_RATIO_SOFT_START 2.0
#define FIREFLY_RATIO_SOFT_END 4.0
#define FIREFLY_LUMA_SOFT_START 1.0
#define FIREFLY_LUMA_SOFT_END 2.5
#define FIREFLY_DROP_BRIGHTEST_MIN_LUMA 1.0
#define FIREFLY_CLAMP_MIN_ABS_LUMA 2.5
#define FIREFLY_DROPED_NEIGHBOR_SCALE 0.5

#define FIREFLY_MIN_REF_FROM_CENTER 0.75
#define FIREFLY_MAX_RATIO 2.0

#include "direct_post_firefly_rejection.glsl"
