#version 460 core
#extension GL_GOOGLE_include_directive : require

#define ATROUS_WITHOUT_VARIANCE 1
#define IN_DIFFUSE_RADIANCE diffuse_radiance_atrous_ping
#define IN_SPECULAR_RADIANCE specular_radiance_atrous_ping

#define OUTPUT_DIFFUSE_RADIANCE out_diffuse_radiance_atrous_pong
#define OUTPUT_SPECULAR_RADIANCE out_specular_radiance_atrous_pong

#define ATROUS_STEP 4
#include "direct_atrous_dual_multipass.glsl"
