#version 460 core
#extension GL_GOOGLE_include_directive : require

#define OUTPUT_IRRADIANCE out_diffuse_direct_sampling_filtered
#define INPUT_IRRADIANCE diffuse_direct
#define LIGHT_ID_SOURCE diffuse_direct_lightdir
#define LIGHT_ID_PACKED_SOURCE diffuse_lightid_packed2x2
#define FILTER_KERNEL_RADIUS 4
#define FILTER_MAX_OFFSETS 8
#define SHADING_NORMAL_DOT_THRESHOLD 0.95

#include "direct_diffuse_sampling_filter.glsl"
