#ifndef DIRECT_DIFFUSE_ATROUS_CONFIG_GLSL_INCLUDED
#define DIRECT_DIFFUSE_ATROUS_CONFIG_GLSL_INCLUDED

#include "denoiser_config.glsl"

#define POSITION_T position_t
#define NORMALS_GS normals_gs
#define MATERIAL_RMXX material_rmxx
#define ATROUS_VARIANCE_OUTPUT out_diffuse_atrous_variance
#define ATROUS_VARIANCE_SOURCE diffuse_atrous_variance

#define SHADING_NORMAL_DOT_THRESHOLD 0.96
#define ATROUS_MAX_STEP DENOISER_MAX_ATROUS_STEP_DIFFUSE
#define ATROUS_MASK_GATE_ENABLE 1
#define ATROUS_MASK_SOURCE diffuse_shadow_mask_debug
#define ATROUS_MASK_SIGMA 0.20
#define ATROUS_MASK_SOFT_EDGE 0.25
#define ATROUS_MASK_FADE_RANGE 0.35
#define ATROUS_LUMA_GATE_ENABLE 1
#define ATROUS_LUMA_THR_MIN 0.07
#define ATROUS_LUMA_THR_AT_HALF_VAR 1.0
#define ATROUS_LUMA_SOFTNESS_MULT 3.2
#define ATROUS_LUMA_STRICT_VAR_CUTOFF 0.0
#define ATROUS_LUMA_STRICT_THR 0.07
#define ATROUS_LUMA_FULL_MIX_VAR 0.45
#define ATROUS_LUMA_REL_EPS 0.03
#define ATROUS_LUMA_MIN_WEIGHT 0.12
#define ATROUS_LUMA_BLEND 0.30
#define ATROUS_LUMA_MIN_WEIGHT_GLOBAL 0.30

#endif

