#ifndef DIRECT_DIFFUSE_ATROUS_CONFIG_GLSL_INCLUDED
#define DIRECT_DIFFUSE_ATROUS_CONFIG_GLSL_INCLUDED

#define POSITION_T position_t
#define NORMALS_GS normals_gs
#define MATERIAL_RMXX material_rmxx

#define SHADING_NORMAL_DOT_THRESHOLD 0.96

#endif

