#ifndef DIRECT_SPECULAR_ATROUS_CONFIG_GLSL_INCLUDED
#define DIRECT_SPECULAR_ATROUS_CONFIG_GLSL_INCLUDED

#define POSITION_T position_t
#define NORMALS_GS normals_gs
#define MATERIAL_RMXX material_rmxx

#define SHADING_NORMAL_EDGE_POWER 6.0
#define SHADING_NORMAL_DOT_TIGHT 0.60
#define SHADING_NORMAL_DOT_RELAXED 0.35
#define GEOM_NORMAL_EDGE_POWER 7.0
#define GEOM_NORMAL_DOT_TIGHT 0.80
#define GEOM_NORMAL_DOT_RELAXED 0.50

#endif

