#version 460 core
#extension GL_GOOGLE_include_directive : require

#define OUTPUT_DIRECT out_diffuse_direct_reconstructed
#define INPUT_DIRECT diffuse_direct_shadowed
#define INPUT_LIGHTDIR diffuse_direct_lightdir

#include "direct_diffuse_atrous_config.glsl"

#define SPATIAL_CONFIDENCE_SCALE DENOISER_SPATIAL_CONFIDENCE_SCALE_DIFFUSE
#define SPATIAL_RADIUS 5.0
#define SPATIAL_USE_FIXED_KERNEL 0
#define SPATIAL_KERNEL_RADIUS 2
#define SPATIAL_FIXED_KERNEL_UNIFORM_WEIGHT 1
#define SPATIAL_RECONSTRUCTION_STAGE_ENABLED DENOISER_ENABLE_SPATIAL_RECONSTRUCTION_DIFFUSE
#undef SHADING_NORMAL_DOT_THRESHOLD
#define SHADING_NORMAL_DOT_THRESHOLD 0.9
#define SPATIAL_ENABLE_ROUGHNESS_GATE 0

#include "direct_spatial_reconstruction.glsl"
