#version 460 core
#extension GL_GOOGLE_include_directive : require

#define OUTPUT_DIRECT out_diffuse_direct_reconstructed
#define INPUT_DIRECT diffuse_direct_shadowed
#define INPUT_LIGHTDIR diffuse_direct_lightdir

#include "direct_diffuse_atrous_config.glsl"

#define SPATIAL_LIGHTDIR_DOT_THRESHOLD 0.92
#define SPATIAL_CONFIDENCE_SCALE 1.2
#define SPATIAL_RADIUS 4.0

#include "direct_spatial_reconstruction.glsl"
