#version 460 core
#extension GL_GOOGLE_include_directive : require

#define OUTPUT_SHADOW out_restir_specular_shadows
#define LIGHT_ID_SOURCE specular_direct_lightdir
#define INPUT_IS_SHADOW_VALUE 1
#define SHADOW_FILTER_USE_SHARED_PINGPONG 1
#define SHADOW_FILTER_OUTPUT_IRRADIANCE 1
#define SHADOW_FILTER_IRRADIANCE_SOURCE specular_direct
#define SHADOW_FILTER_OUTPUT_TEXTURE out_specular_direct_shadowed

#include "direct_shadow_filter.glsl"
