#ifndef DIRECT_DIFFUSE_ATROUS_CONFIG_GLSL_INCLUDED
#define DIRECT_DIFFUSE_ATROUS_CONFIG_GLSL_INCLUDED

#include "denoiser_config.glsl"

#define POSITION_T position_t
#define NORMALS_GS normals_gs
#define MATERIAL_RMXX material_rmxx

#define SHADING_NORMAL_DOT_THRESHOLD 0.96
#define ATROUS_MAX_STEP DENOISER_MAX_ATROUS_STEP_DIFFUSE
#define ATROUS_MASK_GATE_ENABLE 1
#define ATROUS_MASK_SOURCE diffuse_shadow_mask_debug
#define ATROUS_MASK_SIGMA 0.08
#define ATROUS_MASK_SOFT_EDGE 0.10
#define ATROUS_MASK_FADE_RANGE 0.10

#endif

