#version 460
#include "debug.glsl"
#include "utils.glsl"
#include "color_spaces.glsl"
#include "brdf.h"

#define GLSL
#include "ray_interop.h"
#undef GLSL

const int INDIRECT_SCALE = 2;

#define MAX_SAMPLES_COUNT 8.

const float LUMINANCE_THRESHOLD = 2.0;
const float DIELECTRIC_SPECULAR_MULTIPLIER = 0.02; // default value from pbr papers, but 0.04 in Unreal Engine
const int AVERAGE_KERNEL = 2; // big kernel not needed

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba16f) uniform image2D out_diffuse_mixed;
layout(set = 0, binding = 1, rgba16f) uniform image2D out_specular_mixed;

layout(set = 0, binding = 2, rgba16f) uniform readonly image2D diffuse_asvgf_stable;
layout(set = 0, binding = 3, rgba16f) uniform readonly image2D specular_asvgf_stable;

layout(set = 0, binding = 4, rgba16f) uniform readonly image2D diffuse_direct_fs;
layout(set = 0, binding = 5, rgba16f) uniform readonly image2D specular_direct_fs;

// layout(set = 0, binding = 6, rgba16f) uniform readonly image2D indirect_specular;
// layout(set = 0, binding = 7, rgba16f) uniform readonly image2D indirect_diffuse;

layout(set = 0, binding = 8) uniform UBO { UniformBuffer ubo; } ubo;

vec4 fixNaN(vec4 v)
{
    return vec4(
        isnan(v.x) ? 0.0 : v.x,
        isnan(v.y) ? 0.0 : v.y,
        isnan(v.z) ? 0.0 : v.z,
        isnan(v.w) ? 0.0 : v.w
    );
}

vec4 invColor(vec4 v)
{
    return vec4(
        v.x == 0.0 ? 0.0 : 1.0 / v.x,
        v.y == 0.0 ? 0.0 : 1.0 / v.y,
        v.z == 0.0 ? 0.0 : 1.0 / v.z,
        v.w == 0.0 ? 0.0 : 1.0 / v.w
    );
}

vec4 fixRadiance(vec4 v)
{
	return max(vec4(0.0), fixNaN(v));
}

void main() {
	const ivec2 res = ivec2(vec2(ubo.ubo.res) * ubo.ubo.resScale);
	const ivec2 pix = ivec2(gl_GlobalInvocationID);

	if (any(greaterThanEqual(pix, res))) {
		return;
	}

	vec3 diffuse =  fixRadiance(imageLoad(diffuse_asvgf_stable, pix)).rgb +
					fixRadiance(imageLoad(diffuse_direct_fs, pix)).rgb;

	vec3 specular = fixRadiance(imageLoad(specular_asvgf_stable, pix)).rgb +
					fixRadiance(imageLoad(specular_direct_fs, pix)).rgb;

	imageStore(out_diffuse_mixed, pix, vec4(diffuse, 0.0));
	imageStore(out_specular_mixed, pix, vec4(specular, 0.0));
}
