#version 460 core
#extension GL_GOOGLE_include_directive : require

#define INPUT_RADIANCE diffuse_mixed
#define INPUT_RADIANCE_BLURRED diffuse_blured

#define OUTPUT_RADIANCE out_diffuse_asvgf_raw

#define TEMPORAL_POSTFIX _diffuse_asvgf

#define FIREFLY_CLAMP  1.2

#define MAX_ALPHA      0.7
#define MIN_ALPHA      0.02
#define HISTORY_MAX    64.0

#define FIRST_FRAMES_COUNT 3
#define VARIANCE_BLUR_FACTOR 0.1

#include "asvgf_reprojection.glsl"
