#version 460 core
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_control_flow_attributes : require
#extension GL_EXT_control_flow_attributes2 : require

#define GLSL
#include "ray_interop.h"
#undef GLSL

#define VARIANCE_MIN 0.5
#define VARIANCE_MAX 1.0
#define MAX_RESTIR_NORM 8.0
#define MIN_ALPHA 0.02

#define CONF_KERNEL 0

#include "utils.glsl"
#include "noise.glsl"
#include "color_spaces.glsl"

layout(local_size_x=8, local_size_y=8) in;

layout(set = 0, binding = 1, rgba16f) uniform image2D out_diffuse_asvgf;
layout(set = 0, binding = 2, rgba16f) uniform image2D out_specular_asvgf;

layout(set = 0, binding = 3, rgba16f) uniform readonly image2D diffuse_direct;
layout(set = 0, binding = 4, rgba16f) uniform readonly image2D specular_direct;

layout(set = 0, binding=15, rgba32f) uniform image2D prev_temporal_asvgf_diffuse;
layout(set = 0, binding=16, rgba32f) uniform image2D prev_temporal_asvgf_specular;
layout(set = 0, binding=17, rgba32f) uniform image2D out_temporal_asvgf_diffuse;
layout(set = 0, binding=18, rgba32f) uniform image2D out_temporal_asvgf_specular;

layout(set = 0, binding = 9, rgba16f) uniform readonly image2D reprojection_uv;

layout(set = 0, binding = 10) uniform UBO { UniformBuffer ubo; } ubo;

void processLobeTemporal(
    vec3 curr,
    vec3 hist,
    float conf,
    out vec3 outColor,
    out float outVar,
    out float length,
    float prev_length
){
    length = prev_length + 1.0;

    float nonlinear_conf = smoothstep(0.5, 1.0, conf);//pow(smoothstep(0.0, 1.0, conf), 0.3);
    length = mix(1.0, length, nonlinear_conf);

    float alpha = max(MIN_ALPHA, 1.0 / length);

    //outColor = vec3(nonlinear_conf); // debug
    outColor = mix(hist, curr, alpha);

    vec3 d = curr - hist;
    outVar = clamp(dot(d, d), VARIANCE_MIN, VARIANCE_MAX);

    //outColor = curr; // debug current frame
}

void main() {
    const ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    const ivec2 res = ivec2(vec2(ubo.ubo.res) * ubo.ubo.resScale);

	if (any(greaterThanEqual(pix, res)))
		return;

    const ivec2 prev_pix = ivec2(imageLoad(reprojection_uv, pix).xy);

    const vec3 curr_diffuse = imageLoad(diffuse_direct, pix).rgb;
    const vec3 curr_specular = imageLoad(specular_direct, pix).rgb;

    float conf_weight = 0.0;
    float conf_diffuse = 0.0;
    float conf_specular = 0.0;
    for (int x = -CONF_KERNEL; x <= CONF_KERNEL; x++) {
        for (int y = -CONF_KERNEL; y <= CONF_KERNEL; y++) {
            const ivec2 p = pix + ivec2(x, y);
            if (all(greaterThanEqual(p, ivec2(0.))) && all(lessThan(p, res))) {
                conf_weight += 1.0;
                conf_diffuse += imageLoad(diffuse_direct, p).w;
                conf_specular += imageLoad(specular_direct, p).w;
            }
        }
    }
    if (conf_weight > 0.0) {
        conf_diffuse /= conf_weight;
        conf_specular /= conf_weight;
    }

    vec3 diffuse = curr_diffuse;
    float variance_diffuse = 1.0;
    float history_length_diffuse = 1.0;

    vec3 specular = curr_specular;
    float variance_specular = 1.0;
    float history_length_specular = 1.0;

    vec3 prev_diff = curr_diffuse;
    vec3 prev_spec = curr_specular;
    float prev_len_diff = 0.0;
    float prev_len_spec = 0.0;

    if (prev_pix.x >= 0) {
        vec4 pd = imageLoad(prev_temporal_asvgf_diffuse, prev_pix);
        vec4 ps = imageLoad(prev_temporal_asvgf_specular, prev_pix);
        prev_diff = pd.rgb;
        prev_len_diff = pd.w;
        prev_spec = ps.rgb;
        prev_len_spec = ps.w;
    }

    vec3 out_diff = vec3(0.);
    vec3 out_spec = vec3(0.);
    float var_diff = 0., var_spec = 0.;
    float len_diff = 0., len_spec = 0.;

    processLobeTemporal(curr_diffuse, prev_diff, conf_diffuse,
                        out_diff, var_diff, len_diff, prev_len_diff);

    processLobeTemporal(curr_specular, prev_spec, conf_specular,
                       out_spec, var_spec, len_spec, prev_len_spec);
 
    imageStore(out_diffuse_asvgf, pix, vec4(out_diff, var_diff));
    imageStore(out_temporal_asvgf_diffuse, pix, vec4(out_diff, len_diff));

    imageStore(out_specular_asvgf, pix, vec4(out_spec, var_spec));
    imageStore(out_temporal_asvgf_specular, pix, vec4(out_spec, len_spec));
}
