#version 460 core
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_control_flow_attributes : require
#extension GL_EXT_control_flow_attributes2 : require

#define GLSL
#include "ray_interop.h"
#undef GLSL

#include "utils.glsl"
#include "noise.glsl"
#include "debug.glsl"
#include "color_spaces.glsl"

#include "restir_common.glsl"

layout(local_size_x=8, local_size_y=8) in;

layout(set = 0, binding = 1, rgba16f) uniform image2D out_diffuse_asvgf;
layout(set = 0, binding = 2, rgba16f) uniform image2D out_specular_asvgf;
  
layout(set = 0, binding = 3, rgba16f) uniform readonly image2D restir_diffuse;
layout(set = 0, binding = 4, rgba16f) uniform readonly image2D restir_specular;

layout(set = 0, binding=15, rgba32f) uniform image2D prev_temporal_asvgf_diffuse;
layout(set = 0, binding=16, rgba32f) uniform image2D prev_temporal_asvgf_specular;
layout(set = 0, binding=17, rgba32f) uniform image2D out_temporal_asvgf_diffuse;
layout(set = 0, binding=18, rgba32f) uniform image2D out_temporal_asvgf_specular;

layout(set = 0, binding = 9, rgba16f) uniform readonly image2D reprojection_uv;

layout(set = 0, binding = 10) uniform UBO { UniformBuffer ubo; } ubo;

void processLobeTemporal(in vec3 curr, in vec3 hist, float conf, out vec3 outColor, out float outVar, out float length, float prev_length){
    length = prev_length + 1.0;
    length = mix(1.0, length, smoothstep(0.0, 0.5, conf));
    float alpha = 1.0 / length;
    outColor = mix(hist, curr, alpha);
    vec3 dx = curr - hist; vec3 dy = curr - hist;
    outVar = dot(dx,dx) + dot(dy,dy);
}

void main(){
    const ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    const ivec2 res = ivec2(vec2(ubo.ubo.res) * ubo.ubo.resScale);

	if (any(greaterThanEqual(pix, res)))
		return;

    const ivec2 prev_pix = ivec2(imageLoad(reprojection_uv, pix).xy);

    const vec4 diffuse_conf = imageLoad(restir_diffuse, pix);
    const vec3 curr_diffuse = diffuse_conf.rgb;
    const float conf_diffuse = diffuse_conf.w;

    vec4 specular_conf = imageLoad(restir_specular, pix);
    vec3 curr_specular = specular_conf.rgb;
    float conf_specular = specular_conf.w;

    vec3 diffuse = curr_diffuse;
    float variance_diffuse = 1.0;
    float history_length_diffuse = 1.0;

    vec3 specular = curr_specular;
    float variance_specular = 1.0;
    float history_length_specular = 1.0;

    if (prev_pix.x >= 0) {
        vec4 prev_diffuse_history_length = imageLoad(prev_temporal_asvgf_diffuse, prev_pix);
        vec3 prev_diffuse = prev_diffuse_history_length.rgb;
        float prev_diffuse_length = prev_diffuse_history_length.w;
        processLobeTemporal(curr_diffuse, prev_diffuse, conf_diffuse, diffuse, variance_diffuse, history_length_diffuse, prev_diffuse_length);

        vec4 prev_specular_history_length = imageLoad(prev_temporal_asvgf_specular, prev_pix);
        vec3 prev_specular = prev_specular_history_length.rgb;
        float prev_specular_length = prev_specular_history_length.w;
        processLobeTemporal(curr_specular, prev_specular, conf_specular, specular, variance_specular, history_length_specular, prev_specular_length);
    }

    imageStore(out_diffuse_asvgf, pix, vec4(diffuse, variance_diffuse));
    imageStore(out_temporal_asvgf_diffuse, pix, vec4(diffuse, history_length_diffuse));

    imageStore(out_specular_asvgf, pix, vec4(specular, variance_specular));
    imageStore(out_temporal_asvgf_specular, pix, vec4(specular, history_length_specular));
}
