#version 460 core
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_ray_query: require
#extension GL_EXT_control_flow_attributes : require
#extension GL_EXT_control_flow_attributes2 : require

#define SHADING_KERNEL 0
#define SHADING_SAMPLES_COUNT 1
//#define PROJECTED_LIGHT_SAMPLED_UNIFIED 1

//#define STUPID_POLYGON_SAMPLING 1
//#define STUPID_POINT_LIGHT_SAMPLING 1

#define CANDIDATES_COUNT 16
#define CANDIDATES_RAYS false
#define CONFIDENCE_THRESHOLD 1.0
#define POISSON_NOISE_DITHER_SCALE 0.1
#define ANIMATE_PATTERN true
#define FINAL_RAYS true

//#define RANDOM_POISSON_SAMPLING 1

#define GLSL
#include "ray_interop.h"
#undef GLSL

#include "utils.glsl"
#include "noise.glsl"
#include "debug.glsl"
#include "color_spaces.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 1) uniform accelerationStructureEXT tlas;
layout(set = 0, binding = 2) uniform UBO { UniformBuffer ubo; } ubo;

layout(set = 0, binding = 6) uniform sampler2D textures[MAX_TEXTURES];

layout (set = 0, binding = 7) readonly buffer SBOLights { LightsMetadata m; } lights;
layout (set = 0, binding = 8, align = 1) readonly buffer UBOLightClusters {
	LightCluster clusters_[MAX_LIGHT_CLUSTERS];
} light_grid;

layout(set = 0, binding = 10, rgba32f) uniform readonly image2D position_t;
layout(set = 0, binding = 11, rgba16f) uniform readonly image2D normals_gs;
layout(set = 0, binding = 12, rgba8) uniform readonly image2D material_rmxx;
layout(set = 0, binding = 13, rgba8) uniform readonly image2D base_color_a;
//layout(set = 0, binding = 14, rgba32f) uniform readonly image2D frame_blue_noise;

layout(set = 0, binding = 22, rgba16f) uniform writeonly image2D out_diffuse_direct;
layout(set = 0, binding = 23, rgba16f) uniform writeonly image2D out_specular_direct;

layout(set = 0, binding = 24, rgba16f) uniform writeonly image2D out_diffuse_direct_fs;
layout(set = 0, binding = 25, rgba16f) uniform writeonly image2D out_specular_direct_fs;

layout(set = 0, binding = 30, std430) readonly buffer ModelHeaders { ModelHeader a[]; } model_headers;
layout(set = 0, binding = 31, std430) readonly buffer Kusochki { Kusok a[]; } kusochki;
layout(set = 0, binding = 32, std430) readonly buffer Indices { uint16_t a[]; } indices;
layout(set = 0, binding = 33, std430) readonly buffer Vertices { Vertex a[]; } vertices;

// restir
layout(set = 0, binding = 15, rgba32f) uniform readonly image2D diffuse_direct_restir;
layout(set = 0, binding = 16, rgba32f) uniform readonly image2D specular_direct_restir;

layout(set = 0, binding = 21, rgba16f) uniform image2D reprojection_uv;

#define RAY_QUERY

#define LIGHT_POINT 1
#define LIGHT_POLYGON 1

#include "ray_kusochki.glsl"

#ifdef RANDOM_POISSON_SAMPLING
#include "poisson-disk-8x8.glsl"
#endif

#include "restir_common.glsl"

const ivec2 OFFSETS[4] = ivec2[](ivec2(1,0), ivec2(-1,0),
                                  ivec2(0,1), ivec2(0,-1));

vec3 samplingRandom(ivec2 pix, bool previous)
{
#ifdef RANDOM_POISSON_SAMPLING
    uint seed = ANIMATE_PATTERN ? (previous ? ubo.ubo.random_seed : ubo.ubo.random_seed - 1) : 0;
    vec2 poisson_coord = getPoissonCoord(pix + ivec2(int(seed), int(seed>>3)));
    rand01_state = seed + pix.x * 1833 + pix.y * 31337;
    const vec2 poissonNoiseDither = mix(poisson_coord * 0.5 + vec2(0.5), vec2(rand01(),rand01()), POISSON_NOISE_DITHER_SCALE);
    return vec3(poissonNoiseDither, rand01());
#else
    return vec3(rand01(), rand01(), rand01());
#endif
}

vec3 finalShading(inout Reservoir r, vec3 P, vec3 N, vec3 V, MaterialProperties material, SampleContext ctx, vec3 rnd, bool isSpecular, float pdf_mult)
{
    if (r.w_sum == 0.0 || r.w_y == 0.0)
        return vec3(0.0);

    LightResult l = evalUnifiedLight(P, N, V, material, ctx, r.lightIndex, rnd, true, FINAL_RAYS, false);

    vec3 irradiance = isSpecular ? l.specular : l.diffuse;

    return irradiance * pdf_mult * r.w_sum / (r.M * r.w_y);
}

void main(){
#ifdef RAY_TRACE
	const vec2 uv = (gl_LaunchIDEXT.xy + .5) / gl_LaunchSizeEXT.xy * 2. - 1.;
	const ivec2 pix = ivec2(gl_LaunchIDEXT.xy);
#elif defined(RAY_QUERY)
	const ivec2 pix = ivec2(gl_GlobalInvocationID);
	const ivec2 res = ivec2(vec2(ubo.ubo.res) * ubo.ubo.resScale);
	if (any(greaterThanEqual(pix, res))) {
		return;
	}
	const vec2 uv = (gl_GlobalInvocationID.xy + .5) / res * 2. - 1.;
#else
#error You have two choices here. Ray trace, or Rake Yuri. So what it's gonna be, huh? Choose wisely.
#endif

	// FIXME incorrect for reflection/refraction
	const vec4 target    = ubo.ubo.inv_proj * vec4(uv.x, uv.y, 1, 1);
    const vec3 origin    = (ubo.ubo.inv_view * vec4(0, 0, 0, 1)).xyz;
	const vec3 direction = normalize((ubo.ubo.inv_view * vec4(target.xyz, 0)).xyz);
    const vec3 V = -direction;

	const vec4 material_data = imageLoad(material_rmxx, pix);

	MaterialProperties material;
	material.base_color = SRGBtoLINEAR(imageLoad(base_color_a, pix).rgb);
    material.roughness = material_data.r;
    material.metalness = material_data.g;

    const vec4 packed_normal = imageLoad(normals_gs, pix);
    const vec3 geometry_normal = normalDecode(packed_normal.xy);
    const vec3 shading_normal = normalDecode(packed_normal.zw);
    const vec3 N = shading_normal;

	const vec4 pos_t = imageLoad(position_t, pix);
    const vec3 P = pos_t.xyz + geometry_normal * .001;

    uint total = getLightsCountTotal();
    float pdf_mult = float(total);

#ifndef RANDOM_POISSON_SAMPLING
    rand01_state = ubo.ubo.random_seed + pix.x * 1833 + pix.y * 31337;
#endif

    vec3 sampling_rand_curr = samplingRandom(pix, false);

#ifdef RANDOM_POISSON_SAMPLING
    rand01_state = ubo.ubo.random_seed + pix.x * 1833 + pix.y * 31337;
#endif

    float confDiffuse = 0.;
    float confSpecular = 0.;

    const SampleContext ctx = buildSampleContext(P, N, V);

    vec3 diffuse = vec3(0.);
    float diffuse_conf = 0.0;
    float diffuse_w = 0.0;

    vec3 specular = vec3(0.);
    float specular_conf = 0.0;
    float specular_w = 0.0;

    vec3 diffuse_fs = vec3(0.);
    vec3 specular_fs = vec3(0.);

    for (int x = -SHADING_KERNEL; x <= SHADING_KERNEL; x++) {
        for (int y = -SHADING_KERNEL; y <= SHADING_KERNEL; y++) {
            const ivec2 p = clamp(pix + ivec2(x, y), ivec2(0), ivec2(res - 1));

            bool oub_diff = true, oub_spec = true;
            Reservoir rDiffuse = loadReservoir(imageLoad(diffuse_direct_restir, p), oub_diff);
            Reservoir rSpecular = loadReservoir(imageLoad(specular_direct_restir, p), oub_spec);

            for (uint i = 0; i < SHADING_SAMPLES_COUNT; i++) {

                const vec3 rnd = (i == 0) ? sampling_rand_curr : vec3(rand01(), rand01(), rand01());

                if (!oub_diff) {
                    diffuse += finalShading(rDiffuse, P, N, V, material, ctx, rnd, false, pdf_mult);
                    diffuse_conf += rDiffuse.conf;
                    diffuse_w += 1.0;
                }

                if (!oub_spec) {
                    specular += finalShading(rSpecular, P, N, V, material, ctx, rnd, true, pdf_mult);
                    specular_conf += rSpecular.conf;
                    specular_w += 1.0;
                }
            }
        }
    }

    if (diffuse_w > 0.0) {
        diffuse /= diffuse_w;
        diffuse_conf /= diffuse_w;
    }

    if (diffuse_w > 0.0) {
        specular /= specular_w;
        specular_conf /= specular_w;
    }

    {
        LightResult l = sampleFlashlightAndSky(P, N, V, material, sampling_rand_curr, origin, true, FINAL_RAYS, false);
        diffuse_fs += l.diffuse;
        specular_fs += l.specular;
    }

    //imageStore(out_diffuse_direct, pix, vec4(vec3(rDiffuse.conf, 0.0, 1.0 - rDiffuse.conf), rDiffuse.conf)); // debug diffuse confidence
    //imageStore(out_diffuse_direct_restir, pix, vec4(vec3(rSpec.conf, 0.0, 1.0 - rSpec.conf), rSpec.conf)); // debug specular confidence
    //imageStore(out_specular_direct, pix, vec4(vec3(0.0), confSpecular));

    imageStore(out_diffuse_direct, pix, vec4(diffuse, diffuse_conf));
    imageStore(out_specular_direct, pix, vec4(specular, specular_conf));

    imageStore(out_diffuse_direct_fs, pix, vec4(diffuse_fs, 0.0));
    imageStore(out_specular_direct_fs, pix, vec4(specular_fs, 0.0));
}
