#version 460 core
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_ray_query: require
#extension GL_EXT_control_flow_attributes : require
#extension GL_EXT_control_flow_attributes2 : require

#define CANDIDATES_COUNT 8
#define CANDIDATES_RAYS false
#define CONFIDENCE_THRESHOLD 1.0
#define POISSON_NOISE_DITHER_SCALE 0.1
#define ANIMATE_PATTERN true
#define CANDIDATES_BRDF true

#define GLSL
#include "ray_interop.h"
#undef GLSL

#include "utils.glsl"
#include "noise.glsl"
#include "debug.glsl"
#include "color_spaces.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 1) uniform accelerationStructureEXT tlas;
layout(set = 0, binding = 2) uniform UBO { UniformBuffer ubo; } ubo;

layout(set = 0, binding = 6) uniform sampler2D textures[MAX_TEXTURES];

layout (set = 0, binding = 7) readonly buffer SBOLights { LightsMetadata m; } lights;
layout (set = 0, binding = 8, align = 1) readonly buffer UBOLightClusters {
	LightCluster clusters_[MAX_LIGHT_CLUSTERS];
} light_grid;

layout(set = 0, binding = 10, rgba32f) uniform readonly image2D position_t;
layout(set = 0, binding = 11, rgba16f) uniform readonly image2D normals_gs;
layout(set = 0, binding = 12, rgba8) uniform readonly image2D material_rmxx;
layout(set = 0, binding = 13, rgba8) uniform readonly image2D base_color_a;
//layout(set = 0, binding = 14, rgba32f) uniform readonly image2D frame_blue_noise;

layout(set = 0, binding = 22, rgba16f) uniform writeonly image2D out_diffuse_direct_restir;
layout(set = 0, binding = 23, rgba16f) uniform writeonly image2D out_specular_direct_restir;

layout(set = 0, binding = 30, std430) readonly buffer ModelHeaders { ModelHeader a[]; } model_headers;
layout(set = 0, binding = 31, std430) readonly buffer Kusochki { Kusok a[]; } kusochki;
layout(set = 0, binding = 32, std430) readonly buffer Indices { uint16_t a[]; } indices;
layout(set = 0, binding = 33, std430) readonly buffer Vertices { Vertex a[]; } vertices;

// restir
layout(set = 0, binding=15, rgba32f) uniform image2D prev_temporal_res_diffuse;
layout(set = 0, binding=16, rgba32f) uniform image2D prev_temporal_res_specular;
layout(set = 0, binding=17, rgba16f) uniform image2D prev_temporal_res_norm_mat;
layout(set = 0, binding=18, rgba32f) uniform image2D out_temporal_res_diffuse;
layout(set = 0, binding=19, rgba32f) uniform image2D out_temporal_res_specular;
layout(set = 0, binding=20, rgba16f) uniform image2D out_temporal_res_norm_mat;

layout(set = 0, binding = 21, rgba16f) uniform image2D reprojection_uv;

#define RAY_QUERY

#define LIGHT_POINT 1
#define LIGHT_POLYGON 1

#include "ray_kusochki.glsl"
#include "poisson-disk-8x8.glsl"
#include "restir_common.glsl"

const ivec2 OFFSETS[4] = ivec2[](ivec2(1,0), ivec2(-1,0),
                                  ivec2(0,1), ivec2(0,-1));

vec3 samplingRandom(ivec2 pix, bool previous)
{
    uint seed = ANIMATE_PATTERN ? (previous ? ubo.ubo.random_seed : ubo.ubo.random_seed - 1) : 0;
    vec2 poisson_coord = getPoissonCoord(pix + ivec2(int(seed), int(seed>>3)));
    rand01_state = seed + pix.x * 1833 + pix.y * 31337;
    const vec2 poissonNoiseDither = mix(poisson_coord * 0.5 + vec2(0.5), vec2(rand01(),rand01()), POISSON_NOISE_DITHER_SCALE);
    return vec3(poissonNoiseDither, rand01());
}

Reservoir reprojectReservoir(Reservoir r, vec3 P, vec3 N, vec3 V, MaterialProperties material, vec3 rnd, bool isSpecular, out float conf)
{
    LightResult l = evalUnifiedLight(P, N, V, material, r.lightIndex, rnd, CANDIDATES_BRDF, CANDIDATES_RAYS, false);

    conf = restirConfidence(r, luminance(isSpecular ? l.specular : l.diffuse));

    if (conf < rand01()) { // use killing by confidence inside restirConfidence?
        conf = 0.0;
        return reservoirInit();
    }

    return r;
}

vec3 finalShading(inout Reservoir r, vec3 P, vec3 N, vec3 V, MaterialProperties material, vec3 rnd, bool isSpecular, float pdf_mult)
{
    if (r.w_sum == 0.0)
        return vec3(0.0);

    {
        // update weight 

        MaterialProperties weight_mat = material;
        weight_mat.base_color = vec3(1.0);
        weight_mat.metalness = 0.5;

        LightResult l = evalUnifiedLight(P, N, V, weight_mat, r.lightIndex, rnd, CANDIDATES_BRDF, CANDIDATES_RAYS, false);
        
        float curr_y = luminance(isSpecular ? l.specular : l.diffuse);

        r.w_sum += -r.w_y + curr_y;
        r.w_y = curr_y;

        if (curr_y == 0.0)
            return vec3(0.0);
    }

    {
        // final shading with shadow

        LightResult l = evalUnifiedLight(P, N, V, material, r.lightIndex, rnd, true, true, false);

        vec3 irradiance = isSpecular ? l.specular : l.diffuse;

        return irradiance * pdf_mult * r.w_sum / (r.M * r.w_y);
    }
}

void main(){
#ifdef RAY_TRACE
	const vec2 uv = (gl_LaunchIDEXT.xy + .5) / gl_LaunchSizeEXT.xy * 2. - 1.;
	const ivec2 pix = ivec2(gl_LaunchIDEXT.xy);
#elif defined(RAY_QUERY)
	const ivec2 pix = ivec2(gl_GlobalInvocationID);
	const ivec2 res = ivec2(vec2(ubo.ubo.res) * ubo.ubo.resScale);
	if (any(greaterThanEqual(pix, res))) {
		return;
	}
	const vec2 uv = (gl_GlobalInvocationID.xy + .5) / res * 2. - 1.;
#else
#error You have two choices here. Ray trace, or Rake Yuri. So what it's gonna be, huh? Choose wisely.
#endif

	// FIXME incorrect for reflection/refraction
	const vec4 target    = ubo.ubo.inv_proj * vec4(uv.x, uv.y, 1, 1);
	const vec3 direction = normalize((ubo.ubo.inv_view * vec4(target.xyz, 0)).xyz);
    const vec3 V = -direction;

	const vec4 material_data = imageLoad(material_rmxx, pix);

	MaterialProperties material;

    // data for candidates
	material.base_color = vec3(1.0);
    material.roughness = material_data.r;
	material.metalness = 0.5;

    const vec4 packed_normal = imageLoad(normals_gs, pix);
    const vec3 geometry_normal = normalDecode(packed_normal.xy);
    const vec3 shading_normal = normalDecode(packed_normal.zw);
    const vec3 N = shading_normal;

	const vec4 pos_t = imageLoad(position_t, pix);
    const vec3 P = pos_t.xyz + geometry_normal * .001;

    const uint cluster_index = getLightClusterIndex(P);
    const uint total = getLightsCountInCluster(cluster_index);
    const float pdf_mult = float(total);

    ivec2 prevPx = ivec2(imageLoad(reprojection_uv, pix).xy);

    vec3 sampling_rand_curr = samplingRandom(pix, false);
    vec3 sampling_rand_prev = samplingRandom(prevPx, true);

    rand01_state = ubo.ubo.random_seed + pix.x * 1833 + pix.y * 31337;

    float confDiffuse = 0.;
    float confSpecular = 0.;

    Reservoir rDiffuse = Reservoir(0, 0, 0, 0, 0);
    Reservoir rSpec = Reservoir(0, 0, 0, 0, 0);

    if (prevPx.x >= 0 && total > 0) { // avoid reprojection if have no visible lights
        const vec4 prev_norm_mat = imageLoad(prev_temporal_res_norm_mat, pix);

        const vec3 prev_N = normalDecode(prev_norm_mat.xy);

        bool out_of_bound = true;

        {
            Reservoir prevDiffuse = loadReservoir(imageLoad(prev_temporal_res_diffuse, prevPx), out_of_bound);
            if (!out_of_bound)
                rDiffuse = reprojectReservoir(prevDiffuse, P, prev_N, V, material, sampling_rand_prev, false, confDiffuse);
        }
        {
            Reservoir prevSpec = loadReservoir(imageLoad(prev_temporal_res_specular, prevPx), out_of_bound);
            if (!out_of_bound)
                rSpec = reprojectReservoir(prevSpec, P, prev_N, V, material, sampling_rand_prev, true, confSpecular);
        }
    }

    if(total > 0) {
        const bool iterate_all = total <= CANDIDATES_COUNT;

        const uint first_light_id = uint(rand01() * float(total));
        
        LightRandomPickData diff_pick = LightRandomPickData(0,0,0,0,0,-1);
        LightRandomPickData spec_pick = LightRandomPickData(0,0,0,0,0,-1);

        for (uint i = 0; i < CANDIDATES_COUNT; i++) { // always fixed cycle
            const bool out_of_bounds = iterate_all && i >= total;
            if (!out_of_bounds) {
                const uint light_id = iterate_all ? i : (first_light_id + i) % total;

                const LightResult l = evalUnifiedLight(P, N, V, material, light_id, sampling_rand_curr, CANDIDATES_BRDF, CANDIDATES_RAYS, true);

                const float wDiffuse = luminance(l.diffuse);
                const float wSpec = luminance(l.specular);
                
                reservoirUpdate(rDiffuse, l.light_id, wDiffuse, rand01());
                reservoirUpdate(rSpec, l.light_id, wSpec, rand01());
            }
        }
    }

    vec3 diffuse = vec3(0.);
    vec3 specular = vec3(0.);

    // final shading parameters
	material.base_color = SRGBtoLINEAR(imageLoad(base_color_a, pix).rgb);
    material.roughness = material_data.r;
    material.metalness = material_data.g;

    diffuse = finalShading(rDiffuse, P, N, V, material, sampling_rand_curr, false, pdf_mult);
    specular = finalShading(rSpec, P, N, V, material, sampling_rand_curr, true, pdf_mult);

    // if (rDiffuse.w_y > 0.0) {
    //     LightResult l = evalUnifiedLight(P, N, V, material, rDiffuse.lightIndex, sampling_rand_curr, true, false, false);
    //     diffuse = l.diffuse * pdf_mult * rDiffuse.w_sum / (rDiffuse.M * rDiffuse.w_y);
    // }

    // if (rSpec.w_y > 0.0) {
    //     LightResult l = evalUnifiedLight(P, N, V, material, rSpec.lightIndex, sampling_rand_curr, true, false, false);
    //     specular = l.specular * pdf_mult * rSpec.w_sum / (rSpec.M * rSpec.w_y);
    // }

    //imageStore(out_diffuse_direct_restir, pix, vec4(debug_color, confDiffuse)); // debug diffuse confidence
    //imageStore(out_diffuse_direct_restir, pix, vec4(vec3(confDiffuse, 0.0, 1.0 - confDiffuse), confDiffuse)); // debug diffuse confidence
    //imageStore(out_diffuse_direct_restir, pix, vec4(vec3(confSpecular, 0.0, 1.0 - confSpecular), confDiffuse)); // debug specular confidence

    imageStore(out_diffuse_direct_restir, pix, vec4(diffuse, confDiffuse));
    imageStore(out_specular_direct_restir, pix, vec4(specular, confSpecular));
    //imageStore(out_specular_direct_restir, pix, vec4(vec3(0.0), confSpecular));

    imageStore(out_temporal_res_diffuse, pix, saveReservoir(rDiffuse));
    imageStore(out_temporal_res_specular, pix, saveReservoir(rSpec));
    imageStore(out_temporal_res_norm_mat, pix, vec4(normalEncode(shading_normal), material.roughness, material.metalness));
}
