#version 460
#include "debug.glsl"
#include "utils.glsl"
#include "color_spaces.glsl"

#define GLSL
#include "ray_interop.h"
#undef GLSL

const int INDIRECT_SCALE = 2;

#define MAX_SAMPLES_COUNT 8.

const float LUMINANCE_THRESHOLD = 2.0;
const float DIELECTRIC_SPECULAR_MULTIPLIER = 0.02; // default value from pbr papers, but 0.04 in Unreal Engine
const int AVERAGE_KERNEL = 2; // big kernel not needed

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba16f) uniform image2D out_diffuse_reprojected;
layout(set = 0, binding = 1, rgba16f) uniform image2D out_specular_reprojected;

layout(set = 0, binding = 2, rgba16f) uniform readonly image2D light_poly_diffuse;
layout(set = 0, binding = 3, rgba16f) uniform readonly image2D light_poly_specular;

layout(set = 0, binding = 4, rgba16f) uniform readonly image2D light_point_diffuse;
layout(set = 0, binding = 5, rgba16f) uniform readonly image2D light_point_specular;

layout(set = 0, binding = 6, rgba8) uniform readonly image2D base_color_a;

layout(set = 0, binding = 7, rgba32f) uniform readonly image2D position_t;
layout(set = 0, binding = 8, rgba16f) uniform readonly image2D normals_gs;
layout(set = 0, binding = 9, rgba8) uniform readonly image2D material_rmxx;
layout(set = 0, binding = 10, rgba32f) uniform readonly image2D geometry_prev_position;

layout(set = 0, binding = 11, rgba16f) uniform readonly image2D indirect_specular_prefilter;
layout(set = 0, binding = 12, rgba16f) uniform readonly image2D indirect_diffuse_denoised_by_sh;
layout(set = 0, binding = 13, rgba32f) uniform readonly image2D reflection_direction_pdf;

layout(set = 0, binding = 14, rgba16f) uniform image2D out_temporal_diffuse;
layout(set = 0, binding = 15, rgba16f) uniform image2D prev_temporal_diffuse;

layout(set = 0, binding = 16, rgba16f) uniform image2D out_temporal_specular;
layout(set = 0, binding = 17, rgba16f) uniform image2D prev_temporal_specular;

layout(set = 0, binding = 18, rgba16f) uniform image2D out_temporal_moments_ds;
layout(set = 0, binding = 19, rgba16f) uniform image2D prev_temporal_moments_ds;

layout(set = 0, binding = 20, rgba16f) uniform image2D out_temporal_depth;
layout(set = 0, binding = 21, rgba16f) uniform image2D prev_temporal_depth;

layout(set = 0, binding = 22) uniform UBO { UniformBuffer ubo; } ubo;

float luminance(vec3 rgb) { // TODO: include brdf.h
	return dot(rgb, vec3(0.2126f, 0.7152f, 0.0722f));
}

void readNormals(ivec2 uv, out vec3 geometry_normal, out vec3 shading_normal) {
	const vec4 n = imageLoad(normals_gs, uv);
	geometry_normal = normalDecode(n.xy);
	shading_normal = normalDecode(n.zw);
}

float closestColorWeight(vec3 color1, vec3 color2, vec3 sampleColor) {
    float dist1 = dot(color1 - sampleColor, color1 - sampleColor);
    float dist2 = dot(color2 - sampleColor, color2 - sampleColor);
    return (dist1 < dist2) ? 0.0 : 1.0;
}

vec3 restoreSpecular(vec3 decolorized_specular, vec3 base_color, float metalness) {
	// TODO: add fresnel and do like PBR
	const vec3 plasticSpecular = decolorized_specular * DIELECTRIC_SPECULAR_MULTIPLIER;
	const vec3 metalSpecular = decolorized_specular * base_color;
	return mix(plasticSpecular, metalSpecular, metalness);
}

struct TemporalResult {
    vec3 radiance;
    float moment1;
    float moment2;
	float weight;
};

TemporalResult temporalAccumulationInit(vec3 currentSample) {
	TemporalResult r;
	r.radiance = currentSample;
	r.moment1  = luminance(currentSample);
	r.moment2  = r.moment1 * r.moment1;
	r.weight = 0.0;
	return r;
}

TemporalResult temporalAccumulation(vec3 currentSample, vec3 historyRadiance, float historyM1, float historyM2) {
    float variance = max(historyM2 - historyM1 * historyM1, 0.0);
    float sigma = sqrt(variance);

    float k = 5.0; // TODO: move to ubo
    float lo = historyM1 - k * sigma;
    float hi = historyM1 + k * sigma;

    float currLum = luminance(currentSample);
    float clampedLum = currLum;//clamp(currLum, lo, hi);

    float safe = (currLum > 1e-6) ? (clampedLum / currLum) : 1.0;
    vec3 clampedColor = currentSample * safe;

    float historyWeight = clamp(1.0 - sigma * 0.5, 0.05, 0.95);

    vec3 newRadiance = mix(clampedColor, historyRadiance, historyWeight);

    float newM1 = mix(clampedLum, historyM1, historyWeight);
    float newM2 = mix(clampedLum * clampedLum, historyM2, historyWeight);

    TemporalResult r;
    r.radiance = newRadiance;
    r.moment1  = newM1;
    r.moment2  = newM2;
	r.weight = historyWeight;
    return r;
}


vec4 mixIrradianceSamplesCount(vec3 irradiance_src, vec3 irradiance_history, float samples_count, float luminance_threshold)
{
	if (samples_count != 0.) {
		const float blend_weight = 1. / (samples_count + 1.);

		const vec3 irradiance_mixed = mix(irradiance_history, irradiance_src, blend_weight);

		return vec4(irradiance_mixed, min(samples_count + 1., MAX_SAMPLES_COUNT));
	}

	return vec4(irradiance_src, 1.);
}

void main() {
	const ivec2 res = ivec2(vec2(ubo.ubo.res) * ubo.ubo.resScale);
	const ivec2 pix = ivec2(gl_GlobalInvocationID);

	if (any(greaterThanEqual(pix, res))) {
		return;
	}

	const vec3 origin = (ubo.ubo.inv_view * vec4(0., 0., 0., 1.)).xyz;

	const vec3 position = imageLoad(position_t, pix).xyz;
	const float depth = length(origin - position);

	const vec3 base_color = SRGBtoLINEAR(imageLoad(base_color_a, pix).rgb);
	const float metalness = imageLoad(material_rmxx, pix).g;

	vec3 geometry_normal, shading_normal;
	readNormals(pix, geometry_normal, shading_normal);

	vec3 diffuse_src = imageLoad(light_poly_diffuse, pix).rgb +
					   imageLoad(light_point_diffuse, pix).rgb +
					   imageLoad(indirect_diffuse_denoised_by_sh, pix).rgb;

	vec3 specular_src = imageLoad(light_poly_specular, pix).rgb +
					   imageLoad(light_point_specular, pix).rgb +
					   imageLoad(indirect_specular_prefilter, pix).rgb;

	vec3 history_diffuse = diffuse_src;
	vec3 history_specular = specular_src;
	vec3 history_specular_parallax = specular_src;

	float diffuse_samples_count = 1.;
	float specular_samples_count = 1.;

	vec4 diffuse_result = vec4(diffuse_src, 0.0);
	vec4 specular_result = vec4(specular_src, 0.0);
	
	TemporalResult d_tr = temporalAccumulationInit(diffuse_src);
	TemporalResult s_tr = temporalAccumulationInit(specular_src);
	vec4 moments_ds_result = vec4(d_tr.moment1, d_tr.moment2, s_tr.moment1, s_tr.moment2);

	{
		const vec3 prev_position = imageLoad(geometry_prev_position, pix).rgb;
		const vec4 clip_space = inverse(ubo.ubo.prev_inv_proj) * vec4((inverse(ubo.ubo.prev_inv_view) * vec4(prev_position, 1.)).xyz, 1.);
		const vec2 reproj_uv = clip_space.xy / clip_space.w;
		const ivec2 reproj_pix = ivec2((reproj_uv * 0.5 + vec2(0.5)) * vec2(res));
		const vec3 prev_origin = (ubo.ubo.prev_inv_view * vec4(0., 0., 0., 1.)).xyz;
		const float depth_nessesary = length(prev_position - prev_origin);
		const float depth_treshold = 0.01 * clip_space.w;
		float depth_offset_max = depth_treshold;

		if (any(greaterThanEqual(reproj_pix, ivec2(0))) && any(lessThan(reproj_pix, res))) {
			const vec4 history_diffuse_samples = imageLoad( prev_temporal_diffuse, reproj_pix );
			const vec4 history_specular_samples = imageLoad( prev_temporal_specular, reproj_pix );
			const vec4 moments_ds_history = imageLoad( prev_temporal_moments_ds, reproj_pix );
			const float history_depth = imageLoad( prev_temporal_depth, reproj_pix ).r;

			const float depth_offset = abs(history_depth - depth_nessesary);
			if ( depth_offset < depth_offset_max ) {
				d_tr = temporalAccumulation(diffuse_src.rgb, history_diffuse_samples.rgb, moments_ds_history.x, moments_ds_history.y);
				s_tr = temporalAccumulation(specular_src.rgb, history_specular_samples.rgb, moments_ds_history.z, moments_ds_history.w);
				diffuse_result = vec4(d_tr.radiance, 0.0);
				specular_result = vec4(s_tr.radiance, 0.0);
				moments_ds_result = vec4(d_tr.moment1, d_tr.moment2, s_tr.moment1, s_tr.moment2);
			}
		}

		// parallax reprojecting for specular
		float average_ray_length = 0.;
		float ray_length_samples_count = 0.;
		const int AVERAGE_RAY_LENGTH_KERNEL = 1;
		for(int x = -AVERAGE_RAY_LENGTH_KERNEL; x <=AVERAGE_RAY_LENGTH_KERNEL; x++) {
			for(int y = -AVERAGE_RAY_LENGTH_KERNEL; y <=AVERAGE_RAY_LENGTH_KERNEL; y++) {
				const ivec2 p = pix / INDIRECT_SCALE + ivec2(x, y);
				if (any(greaterThanEqual(p, res / INDIRECT_SCALE)) || any(lessThan(p, ivec2(0)))) {
					continue;
				}

				average_ray_length += length(imageLoad( reflection_direction_pdf, p ).xyz);
				ray_length_samples_count += 1.;
			}
		}
		if (ray_length_samples_count > 0. && average_ray_length > 0.) {
			average_ray_length /= ray_length_samples_count;

			//	origin (camera)
			//	       []<          reflection destination
			//		 	| \        (UwU) (reflected in
			//			|   \     /  |    surface texel)
			//			|     \ /    |
			//	--------x------x-----x------------
			//	origin on      ^   reflection on plane
			//	   plane	   |
			//				reflection center
			//		(surface texel in current frame)
			//	  (need to find this in previous frame)
			//		

			const vec3 refl_position = reflect(normalize(position - origin), geometry_normal) * average_ray_length + position;
			const float refl_distance_to_plane = dot(geometry_normal, refl_position - prev_position);
			const vec3 refl_on_plane = refl_position - geometry_normal * refl_distance_to_plane;
			const float prev_distance_to_plane = dot(geometry_normal, prev_origin - prev_position);
			const vec3 prev_origin_on_plane = prev_origin - geometry_normal * prev_distance_to_plane;
			const float refl_center = prev_distance_to_plane / (prev_distance_to_plane + refl_distance_to_plane);
			const vec3 parallax_position = mix(prev_origin_on_plane, refl_on_plane, refl_center);

			const vec4 clip_space = inverse(ubo.ubo.prev_inv_proj) * vec4((inverse(ubo.ubo.prev_inv_view) * vec4(parallax_position, 1.)).xyz, 1.);
			const vec2 parallax_uv = clip_space.xy / clip_space.w;
			const ivec2 parallax_pix = ivec2((parallax_uv * 0.5 + vec2(0.5)) * vec2(res));

			if (any(greaterThanEqual(parallax_pix, ivec2(0))) && any(lessThan(parallax_pix, res))) {
				const float forwardWeight = s_tr.weight;

				const vec4 parallax_specular_samples = imageLoad( prev_temporal_specular, parallax_pix );
				const vec4 parallax_moments_ds_history = imageLoad( prev_temporal_moments_ds, parallax_pix );

				s_tr = temporalAccumulation(specular_src.rgb, parallax_specular_samples.rgb, parallax_moments_ds_history.z, parallax_moments_ds_history.w);

				if (s_tr.weight > forwardWeight) {
					// Parallax reprojection sample is better
					specular_result = vec4(s_tr.radiance, 0.0);
					moments_ds_result.zw = vec2(s_tr.moment1, s_tr.moment2);
				}
			}
		}
	}

	imageStore(out_diffuse_reprojected, pix, diffuse_result);
	imageStore(out_specular_reprojected, pix, specular_result);
	
	imageStore(out_temporal_depth, pix, vec4(depth, 0., 0., 0.)); // reserve other values
	imageStore(out_temporal_diffuse, pix, diffuse_result);
	imageStore(out_temporal_specular, pix, specular_result);
	imageStore(out_temporal_moments_ds, pix, moments_ds_result);
}
