#version 460 core
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_tracing : require

#define GLSL
#include "ray_interop.h"
#undef GLSL

layout(set = 0, binding = 30, std430) readonly buffer ModelHeaders { ModelHeader a[]; } model_headers;

#include "trace_post_pipeline_payload.glsl"

layout(location = PAYLOAD_LOCATION_TRACE_POST) rayPayloadInEXT TracePostRtLegacyPayload payload;
hitAttributeEXT vec2 bary;

void main()
{
	if (model_headers.a[gl_InstanceID].mode != MATERIAL_MODE_DECAL) {
		const uint kusok_index = gl_InstanceCustomIndexEXT + gl_GeometryIndexEXT;
		payload.hits[payload.count] = uvec2(
			tracePostRtPackGeometry(kusok_index, gl_InstanceID),
			gl_PrimitiveID);
		payload.barycentrics[payload.count] = packHalf2x16(bary);
		payload.depths[payload.count] = gl_HitTEXT;
		payload.count++;
		if (payload.count == TRACE_POST_RT_MAX_ENTRIES) {
			terminateRayEXT;
			return;
		}
	}
	ignoreIntersectionEXT;
}
